### ISSUE TITLE
Bootstrap navbar fix is not needed anymore

### ISSUE THREAD

**Issue by kaanguru** [h-enk/hyas#146]
## Description

since Hyas uses bootstrap 5

/** Bootstrap navbar fix (https://git.io/fADqW) */
is not needed anymore.

### Steps to reproduce

Create a hyas site
add bootstrap js to script-footer.html
```
{{ $bootstrap := resources.Get "js/vendor/bootstrap/dist/js/bootstrap.bundle.min.js" -}} 
{{ $js := slice $bootstrap $lazysizes $app | resources.Concat "main.js" -}}
```
heeder.html
```html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavDropdown"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">First</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Second</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

```

### Expected result

There must be a hamburger menu icon on the mobile version of the menu

### Actual result

background image removed by `_variables.scss` file

### Solution

I have sent a pull request.

following lines must be removed from the `_variables.scss` file.
```

/** Bootstrap navbar fix (https://git.io/fADqW) */
$navbar-dark-toggler-icon-bg: none;
$navbar-light-toggler-icon-bg: none;
```

**Comment by h-enk** [comment]
@kaanguru, thanks for indicating this! However, your PR is from your master branch (and not from a fork) — resulting in errors /file changes that are not relevant. To speed things up, I've added the fix myself: 2031c4ebcd9b8405cf9f488b6f6d67049a08c2b5
