### ISSUE TITLE
hyas/docs broken on Netlify

### ISSUE THREAD

**Issue by sean-pwd** [h-enk/hyas#151]
## Description

NPM scripts do not work on windows due to reference to hugo within node modules
Site runs locally but is broken on netlify (presumably due to headers)

### Steps to reproduce

Clone repository.

Remove parts of npm commands before the word hugo to be able to run it, but then browser errors and no external files are run.

Paste the information here as shown by `hyas info`

**Comment by h-enk** [comment]
@sean-pwd, thanks for reporting this. 

> NPM scripts do not work on windows

I can't reproduce this (using both starter theme + child theme)

> Site runs locally but is broken on netlify 

I've noticed that too.  Netlify doesn't work as expected, running Hugo from a bin directory. It's a Netlify caching thing. ("Clear cache and deploy site" will make it run OK).

However, that's not really workable. So, for now (I will raise an issue w/ Netlify), we better use Netlify for running Hugo — edit `./netlify.toml`:

1. Add a Hugo version (preferably the one you're using locally):

    ```toml
    [build.environment]
      NODE_VERSION = "16.3.0"
      NPM_VERSION = "7.16.0"
      HUGO_VERSION = "0.84.4"
    ```
2. Replace all instances of `exec-bin bin/hugo/hugo` w/ `hugo`

That's it (no need to edit `./package.json`)! Now the Netlify deployment process will run as expected — after clearing the Netlify cache (once only):

![Snag_ea6dda](https://user-images.githubusercontent.com/3902872/125617568-37d51bf4-9e4b-46d7-a4e9-669d7668781a.png)

I will (temporarily) update Hyas for this. Hope this helps!

**Comment by sean-pwd** [comment]
Thanks for having a look. I will clone hyas to a new repository after you have updated it so I cant test the new config.
I re-cloned the repository and it worked fine running from the bin folder. I'm not sure why it failed the first time

**Comment by h-enk** [comment]
Updated: https://github.com/h-enk/hyas/pull/156

**Comment by h-enk** [comment]
https://answers.netlify.com/t/deploy-hugo-website-always-fails-when-caching-is-used/42997

**Comment by h-enk** [comment]
84240b5867e7f42b0b28971f3bd787bef152ef38

`hugo-installer` now installs in `node_modules/.bin/hugo` — this folder is cached by Netlify.

Some tests:

- Initial Netlify deploy (runs `npm i`) of `h-enk/hyas` takes 53s: https://app.netlify.com/sites/hyas/deploys/6126512d6745b9e20afaa832
- Repeat Netlify deploy (using cached `node_modules` folder) of `h-enk/hyas` takes 26s: https://app.netlify.com/sites/hyas/deploys/612651067266a00007c66091
