### ISSUE TITLE
hugo server link missing http:

### ISSUE THREAD

**Issue by sean-pwd** [h-enk/hyas#152]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

clone, npm install, npm start
Web Server is available at //localhost:1313/ (bind address 0.0.0.0)

The link is not clickable because http: is missing

### Expected result

I have used an older version of hyas and this bug is not present

### Actual result

What happened.

### Environment

Paste the information here as shown by `hyas info`

windows

**Comment by h-enk** [comment]
Set `baseURL = "http://localhost:1313/"` in `./config/_default/config.toml`.

Or, make the start script your own (recommended), e.g. (handy for testing on local devices):

```
"start:lan": "exec-bin bin/hugo/hugo server --bind=0.0.0.0 --baseURL=http://192.168.1.10 --port=1313",
```

See also the Hugo docs: [hugo server](https://gohugo.io/commands/hugo_server/)

**Comment by sean-pwd** [comment]
I came up with a fix option for this in my most recent commit to my pull request
https://github.com/h-enk/hyas/pull/155/commits/e51e2562150145ac76503cc42caba7e3fe2c41d5

I moved the prod/next baseurl into the _default config as hugo server seems to default to / on dev and this fixes the http: issue
