### ISSUE TITLE
es build

### ISSUE THREAD

**Issue by sean-pwd** [h-enk/hyas#154]
## Summary

Integrate ES build and remove js module mounts/concatenation 
Add js module imports to js file. 

### Basic example

powerfulwebdesign.com.au

### Motivation

Utilise module imports via esbuild. Remove unnecessary mounts of node modules. Makes it easier for users to add new node.js packages after they look at the source code for hyas.

I can do the coding I have already tested it.

**Comment by h-enk** [comment]
That would be better /the preferred way indeed (if supported). 

PR is welcome!

**Comment by sean-pwd** [comment]
PR created
