### ISSUE TITLE
Should KaTeX be removed from hyas?

### ISSUE THREAD

**Issue by timtorres** [h-enk/hyas#296]
## Description

Hi again!👋  Starting here again for another site and just wanted to say great work on the updates that've come out in the last several months. I think this is the strongest Hugo starter I've seen.

[package.json](https://github.com/h-enk/hyas/blob/master/package.json#L40) includes a command for copying KaTeX fonts but I don't see any other references in hyas. Suspect it's leftover from some previous work with [Doks](https://getdoks.org/docs/how-to/extra-features/katex/#1-enable).

https://github.com/h-enk/hyas/blob/f43833f825b22323cc6393f26857f80a9bfe8db2/package.json#L40

### Expected result

Hyas remains separated from Doks

**Comment by h-enk** [comment]
Hi too, and thanks for your kind words! Just because I'm curious, what are you building with Hyas /could you share the website /maybe it's something for the showcase?

Yes, the KaTeX copy command should indeed be removed. I will do that with the next update. Thanks for reporting this.

**Comment by timtorres** [comment]
I had this thought too, but unfortunately we're rebranding within the next year or so I'm afraid the [site](https://www.ey-seren.com/) would be taken down anyway. I'm also unsure from a compliance perspective 🥲

The new site... it's my portfolio site so by nature it may never be finished! I'll let you know.

**Comment by h-enk** [comment]
419d8b28e784df06991349f6c418bcfcc28d9349
