### ISSUE TITLE
Change git command in README

### ISSUE THREAD

**Issue by epogrebnyak** [h-enk/hyas#42]
Maybe change `git clone git@github.com:h-enk/hyas.git my-hyas-site` to more friendly `git clone https://github.com/h-enk/hyas.git my-hyas-site`.

 `git clone git@github.com:h-enk/hyas.git my-hyas-site` gieve me access errors, while `git clone https://github.com/h-enk/hyas.git my-hyas-site` works fine.

**Comment by h-enk** [comment]
Thanks, I will add it the HTTPS clone as the first option — next to the SSH (and GitHub CLI) option.
